/* Native executable tests of real CYM Doom portable contracts. No engine mock. */
#include "doom_contracts.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
static unsigned char fixture[65536];
static size_t fixture_size, reads, max_read;
static void put32(unsigned char *p,uint32_t v){for(unsigned i=0;i<4;i++)p[i]=(unsigned char)(v>>(8*i));}
static bool read_at(void *ctx,uint64_t off,void *dst,size_t n){(void)ctx;reads++;if(n>max_read)max_read=n;if(off>fixture_size||n>fixture_size-off)return false;memcpy(dst,fixture+off,n);return true;}
static const char *names[]={"PLAYPAL","COLORMAP","PNAMES","TEXTURE1","E1M1","THINGS","LINEDEFS","SIDEDEFS","VERTEXES","SEGS","SSECTORS","NODES","SECTORS","REJECT","BLOCKMAP","POSSA1"};
static const unsigned sizes[]={768,8192,4,4,0,10,14,30,4,12,4,28,26,1,8,8};
static void make_wad(void){memset(fixture,0,sizeof(fixture));memcpy(fixture,"IWAD",4);put32(fixture+4,16);put32(fixture+8,12);size_t off=12+16*16;for(unsigned i=0;i<16;i++){unsigned char *e=fixture+12+i*16;put32(e,(uint32_t)off);put32(e+4,sizes[i]);memcpy(e+8,names[i],strlen(names[i]));off+=sizes[i];}fixture_size=off;reads=max_read=0;}
static doom_wad_result validate(void){return doom_wad_validate(read_at,NULL,fixture_size);}
static void wad_valid(void){make_wad();assert(validate()==DOOM_WAD_OK);assert(reads<=40);assert(max_read<=16);}
static void wad_bounds(void){make_wad();fixture_size=11;assert(validate()==DOOM_WAD_BOUNDS);make_wad();put32(fixture+4,0xffffffffu);assert(validate()!=DOOM_WAD_OK);make_wad();put32(fixture+4,0);assert(validate()!=DOOM_WAD_OK);make_wad();put32(fixture+8,0xfffffff0u);assert(validate()!=DOOM_WAD_OK);make_wad();put32(fixture+8,0);assert(validate()!=DOOM_WAD_OK);make_wad();put32(fixture+12,0x7fffffffu);assert(validate()!=DOOM_WAD_OK);make_wad();put32(fixture+16,0xffffffffu);assert(validate()!=DOOM_WAD_OK);make_wad();fixture_size--;assert(validate()!=DOOM_WAD_OK);make_wad();assert(doom_wad_validate(read_at,NULL,UINT64_MAX)!=DOOM_WAD_OK);}
static void wad_resources(void){make_wad();memcpy(fixture,"PWAD",4);assert(validate()==DOOM_WAD_UNSUPPORTED);make_wad();memcpy(fixture+12+4*16+8,"MAP01\0\0\0",8);assert(validate()==DOOM_WAD_UNSUPPORTED);make_wad();put32(fixture+12+4,1);assert(validate()==DOOM_WAD_RESOURCES);make_wad();memset(fixture+12+15*16+8,0,8);assert(validate()==DOOM_WAD_RESOURCES);make_wad();put32(fixture+12+6*16+4,13);assert(validate()==DOOM_WAD_RESOURCES);make_wad();memcpy(fixture+12+7*16+8,"BADNAME",7);assert(validate()==DOOM_WAD_RESOURCES);}
static bool tap(doom_trigger *t,uint32_t ms,bool allowed){assert(!doom_trigger_update(t,ms,true,true,allowed));return doom_trigger_update(t,ms+1,false,true,allowed);}
static void trigger(void){doom_trigger t={0};for(unsigned i=0;i<7;i++)assert(!tap(&t,i*500,true));assert(tap(&t,3500,true));assert(!tap(&t,3600,true));doom_trigger_reset(&t);for(unsigned i=0;i<100;i++)assert(!doom_trigger_update(&t,i,true,true,true));assert(!doom_trigger_update(&t,101,false,true,true));assert(t.count==1);assert(!tap(&t,200,false));assert(t.count==0);for(unsigned i=0;i<7;i++)assert(!tap(&t,300+i*500,true));assert(!tap(&t,7000,true));assert(t.count==1);assert(!doom_trigger_update(&t,7002,true,false,true));assert(t.count==0);doom_trigger_reset(&t);for(unsigned i=0;i<7;i++)assert(!tap(&t,UINT32_MAX-3000+i*300,true));assert(tap(&t,0,true));}
static void scale(void){const int dims[][2]={{240,320},{320,240},{320,480},{480,320}};for(unsigned i=0;i<4;i++){doom_rect r=doom_scale_fit(dims[i][0],dims[i][1]-90);assert(r.w>0&&r.h>0);assert(r.x>=0&&r.y>=0);assert(r.x+r.w<=dims[i][0]&&r.y+r.h<=dims[i][1]-90);assert(r.w*5-r.h*8>=-8&&r.w*5-r.h*8<=8);int x,y;assert(doom_scale_point(r,r.x,r.y,&x,&y));assert(x==0&&y==0);assert(doom_scale_point(r,r.x+r.w-1,r.y+r.h-1,&x,&y));assert(x<320&&y<200);assert(!doom_scale_point(r,-1,-1,&x,&y));}doom_rect bad=doom_scale_fit(0,20);assert(bad.w==0);int x,y;assert(doom_rotate_point(240,320,1,10,20,&x,&y)&&x==299&&y==10);assert(doom_rotate_point(240,320,3,10,20,&x,&y)&&x==20&&y==229);assert(!doom_rotate_point(240,320,0,240,0,&x,&y));}
static void keys(void){doom_keys k={0};unsigned key;bool pressed;doom_keys_set(&k,DOOM_KEY_FORWARD|DOOM_KEY_FIRE);unsigned n=0;while(doom_keys_next(&k,&key,&pressed)){assert(pressed);n++;}assert(n==2);assert(!doom_keys_next(&k,&key,&pressed));doom_keys_set(&k,DOOM_KEY_BACK);n=0;unsigned releases=0;while(doom_keys_next(&k,&key,&pressed)){n++;releases+=!pressed;}assert(n==3&&releases==2);doom_keys_set(&k,0);assert(doom_keys_next(&k,&key,&pressed)&&!pressed);assert(!doom_keys_next(&k,&key,&pressed));assert(doom_touch_keys(240,320,20,235,true)==DOOM_KEY_LEFT);assert(doom_touch_keys(240,320,100,235,true)==DOOM_KEY_FORWARD);assert(doom_touch_keys(240,320,220,315,true)==DOOM_KEY_EXIT);assert(doom_touch_keys(240,320,20,235,false)==0);assert(doom_touch_keys(240,320,-1,235,true)==0);}
static unsigned cleaned[8],clean_count;
static void cleanup(void *p){cleaned[clean_count++]=(unsigned)(uintptr_t)p;}
static void lifecycle(void){doom_lifecycle l={0};assert(doom_lifecycle_begin(&l));assert(!doom_lifecycle_begin(&l));assert(doom_lifecycle_own(&l,cleanup,(void *)(uintptr_t)1));assert(doom_lifecycle_own(&l,cleanup,(void *)(uintptr_t)2));doom_lifecycle_fail(&l);assert(!doom_lifecycle_joined(&l));assert(clean_count==0);doom_lifecycle_worker_done(&l);assert(doom_lifecycle_joined(&l));doom_lifecycle_cleanup(&l);assert(clean_count==2&&cleaned[0]==2&&cleaned[1]==1);doom_lifecycle_cleanup(&l);assert(clean_count==2);assert(l.phase==DOOM_IDLE);for(unsigned repeat=0;repeat<20;repeat++){assert(doom_lifecycle_begin(&l));assert(doom_lifecycle_running(&l));doom_lifecycle_stop(&l);assert(!doom_lifecycle_running(&l));doom_lifecycle_worker_done(&l);doom_lifecycle_cleanup(&l);assert(l.phase==DOOM_IDLE);}assert(doom_lifecycle_begin(&l));for(unsigned i=0;i<DOOM_OWNERS_MAX;i++)assert(doom_lifecycle_own(&l,cleanup,NULL));assert(!doom_lifecycle_own(&l,cleanup,NULL));/* clear dummy registry to keep test cleanup buffer bounded */l.owned_count=0;doom_lifecycle_fail(&l);doom_lifecycle_worker_done(&l);doom_lifecycle_cleanup(&l);}
static void gate(void){uint8_t digest[32]={0x73,0x23,0xbc,0xc1,0x68,0xc5,0xa4,0x5f,0xf1,0x07,0x49,0xb3,0x39,0x96,0x0e,0x98,0x31,0x47,0x40,0xa7,0x34,0xc3,0x0d,0x4b,0x9f,0x33,0x37,0x00,0x1f,0x9e,0x70,0x3d};assert(doom_wad_trusted_hash(digest));digest[0]^=1;assert(!doom_wad_trusted_hash(digest));doom_gate g={.supported=true,.idle=true,.sd_ready=true,.licensed=true,.assets_valid=true,.psram_free=7*1024*1024,.psram_largest=6*1024*1024};assert(doom_gate_ready(g));g.licensed=false;assert(!doom_gate_ready(g));g.licensed=true;g.psram_largest--;assert(!doom_gate_ready(g));g.psram_largest++;g.psram_free=6*1024*1024;assert(!doom_gate_ready(g));g.psram_free=7*1024*1024;g.idle=false;assert(!doom_gate_ready(g));g.idle=true;g.supported=false;assert(!doom_gate_ready(g));doom_lifecycle l={0};assert(!doom_lifecycle_callback_valid(&l,0));assert(doom_lifecycle_begin(&l));uint32_t generation=l.generation;assert(doom_lifecycle_callback_valid(&l,generation));doom_lifecycle_stop(&l);assert(!doom_lifecycle_callback_valid(&l,generation));doom_lifecycle_worker_done(&l);doom_lifecycle_cleanup(&l);assert(doom_lifecycle_begin(&l));assert(!doom_lifecycle_callback_valid(&l,generation));doom_lifecycle_worker_done(&l);doom_lifecycle_cleanup(&l);}
int main(int argc,char **argv){assert(argc==2);if(!strcmp(argv[1],"wad-valid"))wad_valid();else if(!strcmp(argv[1],"wad-bounds"))wad_bounds();else if(!strcmp(argv[1],"wad-resources"))wad_resources();else if(!strcmp(argv[1],"trigger"))trigger();else if(!strcmp(argv[1],"scale"))scale();else if(!strcmp(argv[1],"keys"))keys();else if(!strcmp(argv[1],"lifecycle"))lifecycle();else if(!strcmp(argv[1],"gate"))gate();else return 2;printf("PASS %s: production helpers; synthetic parser fixtures, no game/runtime claim\n",argv[1]);return 0;}
